### ISSUE TITLE
License for CoSEM

### ISSUE THREAD

**Issue by raymondng76** [wdwgonzales/CoSEM#1]
Hi!
Thank you very much for releasing the corpus to the public.
May I ask what is the license for the corpus? and can it be used for commercial purposes?

We are pre-training Large Language Models specifically for Southeast Asian region and we would very much like to include this corpus into our pre-training dataset.

https://aisingapore.org/aiproducts/sea-lion/

Thank you!

**Comment by wdwgonzales** [comment]
Hello! The license for this dataset has just been added (see ReadMe). Thank you!
